### ISSUE TITLE
Running the current site using Python 2.7

### ISSUE THREAD

**Issue by isedwards** [IDEMSInternational/molo-iogt#2]
@nathanbaleeta, @michaelzhang608

Using the `master` branch:
- Are you both able to get a local copy of the project running using Python 2.7?
- Do the [tests run successfully](https://github.com/IDEMSInternational/molo-iogt/tree/master#testing)?
- Does the site work as expected when you [run the development server](https://github.com/IDEMSInternational/molo-iogt/tree/master#getting-started)?

Can you tell me about your development setup? Are you using Python on Windows or on Linux etc.

**Comment by michaelzhang608** [comment]
@isedwards ok, working on it! (I'm going to use the virtualenv Python package on macOS Catalina)

**Comment by michaelzhang608** [comment]
@isedwards I got the master branch successfully running on Python 2.7 locally, however, I had to run `pip install 'django-appconf==1.0.3' --force-reinstall` to downgrade the django-appconf version to work with Python 2.7.


This is my output after running `py.test` (I'm not sure; is 75% cover good enough or not?):
```
---------- coverage: platform darwin, python 2.7.16-final-0 ----------
Name                                                     Stmts   Miss  Cover
----------------------------------------------------------------------------
iogt/__init__.py                                             0      0   100%
iogt/admin.py                                                3      1    67%
iogt/celery.py                                               8      8     0%
iogt/middleware.py                                          85      3    96%
iogt/migrations/0001_initial.py                              5      5     0%
iogt/migrations/0002_create_importers_group.py              11     11     0%
iogt/migrations/0003_convert_recomended_articles.py         34     34     0%
iogt/migrations/0004_create_me_expert.py                    51     51     0%
iogt/migrations/0005_remove_reaction_question_index.py      11     11     0%
iogt/migrations/__init__.py                                  0      0   100%
iogt/processors.py                                           3      0   100%
iogt/settings/__init__.py                                    1      0   100%
iogt/settings/base.py                                      114      7    94%
iogt/settings/dev.py                                         9      0   100%
iogt/settings/docker.py                                     30     30     0%
iogt/settings/production.py                                 17     17     0%
iogt/templatetags/__init__.py                                0      0   100%
iogt/templatetags/pagination.py                             18      0   100%
iogt/tests/__init__.py                                       0      0   100%
iogt/tests/test_middleware.py                              144      0   100%
iogt/tests/test_pagination.py                               85      0   100%
iogt/tests/test_views.py                                    52      0   100%
iogt/urls.py                                                24      5    79%
iogt/views.py                                               25      0   100%
iogt/wsgi.py                                                 4      4     0%
----------------------------------------------------------------------------
TOTAL                                                      734    187    75%

====== 23 passed, 201809 warnings in 200.38 seconds ====
```

**Comment by isedwards** [comment]
I've not really looked into the code yet, or looked at the commit history, but there doesn't seem to be that much here in terms of custom code. There are also very few [migrations](https://github.com/IDEMSInternational/molo-iogt/tree/d9598ec759454dd49f859290bf5b7f3442059b70/iogt/migrations).

1. The relatively large number of commits may be due to work on the language translation files in `/locale`, there's also some work on custom [templates](https://github.com/IDEMSInternational/molo-iogt/tree/master/iogt/templates) and [CSS](https://github.com/IDEMSInternational/molo-iogt/tree/master/iogt/styles/iogt).  I've added #4 to investigate this.
2. When we complete the upgrade we should make some recommendations, including whether we should work on increasing the test coverage. Recommendations should be recorded in #1.

**Comment by nathanbaleeta** [comment]
I'm running on Linux and the site works as expected. I got 73% coverage when I ran the tests.

**Comment by isedwards** [comment]
Could you paste the output just so that we have a record of the difference?  I'm not sure whether it's worth investigating, it could be due to line endings.

**Comment by isedwards** [comment]
From the work in #7, it looks like the code is already Python 3 ready... the problem instead is that Python 2 is being used in production along with old version of Django and Wagtail that are no longer supported.

In a different virtualenv (using Python 3), could you both test the `master` branch (either before or after the changes made by 2to3 - I don't think it matters) and paste the resutls of the automated tests here?

**Comment by michaelzhang608** [comment]
These are my test results when running on Python 3 (exactly the same results as when I ran on Python 2):
```
---------- coverage: platform darwin, python 3.6.4-final-0 -----------
Name                                                     Stmts   Miss  Cover
----------------------------------------------------------------------------
iogt/__init__.py                                             0      0   100%
iogt/admin.py                                                3      1    67%
iogt/celery.py                                               8      8     0%
iogt/middleware.py                                          85      3    96%
iogt/migrations/0001_initial.py                              5      5     0%
iogt/migrations/0002_create_importers_group.py              11     11     0%
iogt/migrations/0003_convert_recomended_articles.py         34     34     0%
iogt/migrations/0004_create_me_expert.py                    51     51     0%
iogt/migrations/0005_remove_reaction_question_index.py      11     11     0%
iogt/migrations/__init__.py                                  0      0   100%
iogt/processors.py                                           3      0   100%
iogt/settings/__init__.py                                    1      0   100%
iogt/settings/base.py                                      114      7    94%
iogt/settings/dev.py                                         9      0   100%
iogt/settings/docker.py                                     30     30     0%
iogt/settings/production.py                                 17     17     0%
iogt/templatetags/__init__.py                                0      0   100%
iogt/templatetags/pagination.py                             18      0   100%
iogt/tests/__init__.py                                       0      0   100%
iogt/tests/test_middleware.py                              144      0   100%
iogt/tests/test_pagination.py                               85      0   100%
iogt/tests/test_views.py                                    52      0   100%
iogt/urls.py                                                24      5    79%
iogt/views.py                                               25      0   100%
iogt/wsgi.py                                                 4      4     0%
----------------------------------------------------------------------------
TOTAL                                                      734    187    75%

================================================ 23 passed, 201810 warnings in 153.24s (0:02:33)
```

**Comment by nathanbaleeta** [comment]
> Could you paste the output just so that we have a record of the difference?

---------- coverage: platform linux2, python 2.7.15-final-0 ----------
Name                                                                                                                                 Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------------------------------------------
iogt/__init__.py                                                                                                                           0      0   100%
iogt/admin.py                                                                                                                              3      1    67%
iogt/celery.py                                                                                                                              8      8     0%
iogt/middleware.py                                                                                                                    85     16    81%
iogt/migrations/0001_initial.py                                                                                                    5      5     0%
iogt/migrations/0002_create_importers_group.py                                                                     11     11     0%
iogt/migrations/0003_convert_recomended_articles.py                                                            34     34     0%
iogt/migrations/0004_create_me_expert.py                                                                               51     51     0%
iogt/migrations/0005_remove_reaction_question_index.py                                                       11     11     0%
iogt/migrations/__init__.py                                                                                                          0      0   100%
iogt/processors.py                                                                                                                       5      0   100%
iogt/settings/__init__.py                                                                                                               1      0   100%
iogt/settings/base.py                                                                                                                115      7    94%
iogt/settings/dev.py                                                                                                                    10      0   100%
iogt/settings/docker.py                                                                                                               30     30     0%
iogt/settings/production.py                                                                                                         17     17     0%
iogt/templatetags/__init__.py                                                                                                       0      0   100%
iogt/templatetags/pagination.py                                                                                                  18      0   100%
iogt/tests/__init__.py                                                                                                                     0      0   100%
iogt/tests/test_middleware.py                                                                                                    144      0   100%
iogt/tests/test_pagination.py                                                                                                        85      0   100%
iogt/tests/test_views.py                                                                                                                52      0   100%
iogt/urls.py                                                                                                                                    24      5    79%
iogt/views.py                                                                                                                                 33      4    88%
iogt/wsgi.py                                                                                                                                     4      4     0%
---------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                                         746    204    73%

**Comment by nathanbaleeta** [comment]
> Could you paste the output just so that we have a record of the difference?

![2to3](https://user-images.githubusercontent.com/8824104/91467278-09c88d00-e899-11ea-988d-dd2d21911a9f.png)

**Comment by isedwards** [comment]
@nathanbaleeta - I didn't realise that you had failing tests (as well as the lower test coverage). Could you run pytest with -rf to get it to print a list of failed tests at the end?

**Comment by nathanbaleeta** [comment]
================================================================ short test summary info ================================================================
FAILED iogt/tests/test_middleware.py::TestSSLRedirectMiddleware::test_no_redirect_for_home_page - ImportError: No module named request
FAILED iogt/tests/test_middleware.py::TestSSLRedirectMiddleware::test_no_redirect_when_secure - KeyError: 'en'
FAILED iogt/tests/test_middleware.py::TestSSLRedirectMiddleware::test_no_redirect_with_https - KeyError: 'en'
FAILED iogt/tests/test_middleware.py::TestSSLRedirectMiddleware::test_redirect_when_not_secure - KeyError: 'en'
FAILED iogt/tests/test_middleware.py::TestGoogleAnalyticsMiddleware::test_ga_middleware - KeyError: 'en'
FAILED iogt/tests/test_middleware.py::TestFaceBookPixelHistoryCounter::test_less_that_3_page_views - KeyError: 'en'
FAILED iogt/tests/test_middleware.py::TestFaceBookPixelHistoryCounter::test_more_that_3_page_views - KeyError: 'en'
FAILED iogt/tests/test_middleware.py::TestReferrerPolicyMiddleware::test_referrer_policy_middleware - KeyError: 'en'
FAILED iogt/tests/test_pagination.py::RegistrationViewTest::test_fifteenth_page_pagination - KeyError: 'en'
FAILED iogt/tests/test_pagination.py::RegistrationViewTest::test_fifth_page_pagination - KeyError: 'en'
FAILED iogt/tests/test_pagination.py::RegistrationViewTest::test_first_page_pagination - KeyError: 'en'
FAILED iogt/tests/test_pagination.py::RegistrationViewTest::test_fourteenth_page_pagination - KeyError: 'en'
FAILED iogt/tests/test_pagination.py::RegistrationViewTest::test_second_page_pagination - KeyError: 'en'
FAILED iogt/tests/test_pagination.py::RegistrationViewTest::test_sixteenth_page_pagination - KeyError: 'en'
FAILED iogt/tests/test_pagination.py::RegistrationViewTest::test_third_page_pagination - KeyError: 'en'
FAILED iogt/tests/test_views.py::ViewsTestCase::test_health_good - KeyError: 'en'
FAILED iogt/tests/test_views.py::ViewsTestCase::test_health_no_interface_set - KeyError: 'en'
FAILED iogt/tests/test_views.py::ViewsTestCase::test_health_stuck - KeyError: 'en'
FAILED iogt/tests/test_views.py::ViewsTestCase::test_maintenance_mode - KeyError: 'en'
FAILED iogt/tests/test_views.py::ViewsTestCase::test_reporting_comment - KeyError: 'en'
================================================= 20 failed, 3 passed, 16237 warnings in 12.77 seconds ==================================================

**Comment by nathanbaleeta** [comment]
> @nathanbaleeta - I didn't realise that you had failing tests (as well as the lower test coverage). Could you run pytest with -rf to get it to print a list of failed tests at the end?

![pytest](https://user-images.githubusercontent.com/8824104/91535621-16da9000-e91c-11ea-8985-e47137604f5c.png)

**Comment by isedwards** [comment]
@nathanbaleeta - before you start work on a new branch, could you have a look at why your tests above are failing?

Let us know if there's anything we can do to help.

**Comment by nathanbaleeta** [comment]
The tests on which my local instance are failing are both related to class [TestFaceBookPixelHistoryCounter](https://github.com/IDEMSInternational/molo-iogt/blob/develop/iogt/tests/test_middleware.py) and methods `test_more_that_3_page_views` and `test_less_that_3_page_views` on lines `227` and `241`. Both tests check  **if the no script html tag exists**. Below is a snapshot for further detail:

![FAILED](https://user-images.githubusercontent.com/8824104/92604499-42189400-f2b9-11ea-95b1-ccaad5e2b2f0.png)

**Comment by isedwards** [comment]
The reason that Michael's tests passed is because he was testing the `master` branch ([as originally intended](https://github.com/IDEMSInternational/molo-iogt/issues/2#issue-685285941)).

The Facebook tracking tests above fail because the corresponding middleware has been disabled on the `develop` branch. I've fixed the tests [here](https://github.com/unicef/molo-iogt/pull/22), but there are so many warnings generated during the tests that the Travis build terminates early, so it still needs more work.
