### ISSUE TITLE
Run 2to3 on existing codebase

### ISSUE THREAD

**Issue by isedwards** [IDEMSInternational/molo-iogt#5]
- [x] Create a new branch from `master` called `2to3`
- [x] Run the [2to3](https://docs.python.org/2/library/2to3.html) automated tool using the `-w` flag to overwrite current files with required changes and `-n` to prevent the creation of backup files on this branch
- [x] Commit the changes (as a single commit) and open a pull-request

**Comment by nathanbaleeta** [comment]
Seem to get the error below when I attempt to push the changes upstream using "**git push --set-upstream origin 2to3**"

**Error**:
remote: Permission to IDEMSInternational/molo-iogt.git denied to nathanbaleeta.
fatal: unable to access 'https://github.com/IDEMSInternational/molo-iogt.git/': The requested URL returned error: 403,

**Comment by isedwards** [comment]
@dannyparsons can you give write access to this repository to @nathanbaleeta and @michaelzhang608?

**Comment by dannyparsons** [comment]
Done, invites sent.

**Comment by nathanbaleeta** [comment]
Raised the pull request for 2to3.
