### ISSUE TITLE
Add support for Google OneBox

### ISSUE THREAD

**Issue by isedwards** [IDEMSInternational/molo-iogt#9]
Create a feature within IoGT’s CMS that allows content managers to identify a mark-up for How-
To, FAQ, and Video. This ‘selection’ within an article’s settings should then map features within
the article’s body (such as headings, images, and numbered lists) to all relevant recommended
properties JSON mark-up file. Information / guidance boxes within the CMS should provide
guidance to content managers when configuring content for mark-up.

Modify IoGT code base to include Google OneBox algorithm:

- 1.2.3 IoGT CMS need to classify IoGT content into categories, such as categories of IOGT
pages, such as, be articles, announcements, factchecks, FAQs, etc. and generate
JSON-LD pages, refer to:

  - 1.2.3.1 https://support.google.com/gsa/answer/6329206?hl=en
  - 1.2.3.2 https://developers.google.com/search/docs/data-types/article
  - 1.2.3.3 https://developers.google.com/search/docs/data-types/special-announcements
  - 1.2.3.4 https://developers.google.com/search/docs/data-types/factcheck
  - 1.2.3.5 https://developers.google.com/search/docs/data-types/faqpage

- 1.2.4 Follow the documentation and load the markup on schema.org, to configure IOGT
for structured data. Refer to FAQ guidance, Wagtail library (the underlying CMS)
https://github.com/neon-jungle/wagtail-schema.org

- 1.2.5 Assess the use of existing library as a viable way forward or if there is a need to
develop replacements?

- 1.2.6 Establish a process and tool for development/backlog management, preferably
GitHub to ensure fully Open Source solution.

**Comment by nathanbaleeta** [comment]
In response to 1.2.6, I would like to propose adopting **scrum** as an agile process/ framework for developing and delivering software releases for IoGT. Scrum has an initial emphasis on **software development** and works well for **small distributed teams** of less than 10 members. 
The key roles would be: **Scrum master**, **Product owner** and **development team** which fits well with the current structure. 

The available work can be broken down into goals that can be completed within time boxed iterations, called **sprints**. 
The Scrum Team track progress in 15-minute time-boxed daily meetings, called **daily scrums** for **introspection**, however we could instead have **weekly scrums** instead for better convenience. At the end of the sprint, the team holds **sprint review**, to demonstrate the work done, and **sprint retrospective** to continuously improve.

**Comment by isedwards** [comment]
@nathanbaleeta - let's break these out into separate issues to continue the discussion.  I've opened #10 and #11.
